name: Build Package

on:
  push:
    branches:
    - workflow
    paths:
    - 'x86_64/**'
  pull_request:
    paths:
    - 'x86_64/**'
  workflow_dispatch:
    inputs:
      packages:
        description: "A space-separated names of packages selected for rebuilding"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: prepare build env
      run: |
        # Basics
        # Clone and install required deps
        mkdir -p ~/DRUNK
        cd ~/DRUNK
        git clone https://git.it-kuny.ch/drunk/setup.git setup --depth=10
        git clone https://github.com/Drunk-Linux/drunk-pkgbuild -b workflow pkgbuild --depth=50
        ln -sf setup/drunk.sh drunk
      
        # Free up space ( for this workflow )
        #sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|libmono|php)') \
        #liblldb-6.0 libllvm6.0:amd64 mono-runtime-common monodoc-manual powershell ruby
      
        # sudo apt autoremove -yq
      
        # sudo rm -rf /opt/hostedtoolcache /usr/local /usr/share/dotnet /usr/share/swift
      
        # Now prepare drunk build env
        # As were running in ubuntu env then we need to bypass normal checks of script
        touch setup/checks/is_checked
    
    - name: Build Packages
      run: |
        # Get list of packages to build
        cd ~/DRUNK/pkgbuild
        ./changed.sh > ../list
        cd ..
      
        cat list
      
        # Build the packages in docker env
        ./drunk -d -b -c $(cat list)
